"""subo todas las tablas de mi proyecto

Revision ID: 395cd0550770
Revises: 
Create Date: 2025-05-26 07:31:22.812628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395cd0550770'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('noticias',
    sa.Column('id_noticia', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_noticia')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=60), nullable=True),
    sa.Column('apellido_usuario', sa.String(length=60), nullable=True),
    sa.Column('correo_usuario', sa.String(length=60), nullable=True),
    sa.Column('contrasena_usuario', sa.String(length=60), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('articulos',
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.PrimaryKeyConstraint('id_articulo')
    )
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id_articulo'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    op.drop_table('articulos')
    op.drop_table('usuarios')
    op.drop_table('noticias')
    op.drop_table('roles')
    op.drop_table('categorias')
    # ### end Alembic commands ###
