"""tabla de comentarios con relaciones creada

Revision ID: 5a4ffb8c5489
Revises: a3df24489e20
Create Date: 2025-05-19 19:07:19.662168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4ffb8c5489'
down_revision: Union[str, None] = 'a3df24489e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id_comentario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('articulo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['articulo_id'], ['articulos.id_articulo'], ),
    sa.PrimaryKeyConstraint('id_comentario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    # ### end Alembic commands ###
