"""subo actualizaciones de tablas

Revision ID: 68c846cab6bb
Revises: 395cd0550770
Create Date: 2025-05-26 10:01:03.842847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '68c846cab6bb'
down_revision: Union[str, None] = '395cd0550770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagenes',
    sa.Column('id_imagen', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_imagen')
    )
    op.drop_table('articulos')
    op.add_column('comentarios', sa.Column('noticia_id', sa.Integer(), nullable=True))
    op.add_column('comentarios', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.drop_constraint('comentarios_ibfk_1', 'comentarios', type_='foreignkey')
    op.create_foreign_key(None, 'comentarios', 'noticias', ['noticia_id'], ['id_noticia'])
    op.create_foreign_key(None, 'comentarios', 'usuarios', ['usuario_id'], ['id_usuario'])
    op.drop_column('comentarios', 'articulo_id')
    op.add_column('noticias', sa.Column('titulo', sa.String(length=60), nullable=True))
    op.add_column('noticias', sa.Column('introducción', sa.String(length=200), nullable=True))
    op.add_column('noticias', sa.Column('contenido', sa.String(length=2000), nullable=True))
    op.add_column('noticias', sa.Column('Imagen', sa.String(length=200), nullable=True))
    op.drop_column('noticias', 'descripcion')
    op.drop_column('noticias', 'nombre')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('nombre', mysql.VARCHAR(length=60), nullable=True))
    op.add_column('noticias', sa.Column('descripcion', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('noticias', 'Imagen')
    op.drop_column('noticias', 'contenido')
    op.drop_column('noticias', 'introducción')
    op.drop_column('noticias', 'titulo')
    op.add_column('comentarios', sa.Column('articulo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.drop_constraint(None, 'comentarios', type_='foreignkey')
    op.create_foreign_key('comentarios_ibfk_1', 'comentarios', 'articulos', ['articulo_id'], ['id_articulo'])
    op.drop_column('comentarios', 'usuario_id')
    op.drop_column('comentarios', 'noticia_id')
    op.create_table('articulos',
    sa.Column('id_articulo', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', sa.DATE(), nullable=True),
    sa.Column('estado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('nombre', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('contenido', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('noticia_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], name='articulos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_articulo'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('imagenes')
    # ### end Alembic commands ###
