"""tabla de usuarios creada

Revision ID: 7eba160a9653
Revises: 1d470fb3ffb6
Create Date: 2025-05-19 18:47:26.519919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eba160a9653'
down_revision: Union[str, None] = '1d470fb3ffb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=60), nullable=True),
    sa.Column('apellido_usuario', sa.String(length=60), nullable=True),
    sa.Column('correo_usuario', sa.String(length=60), nullable=True),
    sa.Column('contrasena_usuario', sa.String(length=60), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
