"""tabla de articulo creada con relaciones actualizadas

Revision ID: a3df24489e20
Revises: 7eba160a9653
Create Date: 2025-05-19 18:56:21.090026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3df24489e20'
down_revision: Union[str, None] = '7eba160a9653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulos',
    sa.Column('id_articulo', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.Date(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('nombre', sa.String(length=60), nullable=True),
    sa.Column('contenido', sa.String(length=200), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id_noticia'], ),
    sa.PrimaryKeyConstraint('id_articulo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articulos')
    # ### end Alembic commands ###
